# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-01 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('link', models.CharField(max_length=100, verbose_name='\u65b0\u95fb\u94fe\u63a5')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u6b63\u6587')),
                ('stemming', models.TextField(verbose_name='\u65b0\u95fb\u4e3b\u5e72')),
                ('cluster', models.IntegerField(default=0, verbose_name='\u6240\u5728\u7c07')),
                ('distance', models.FloatField(default=0.0, verbose_name='\u8ddd\u79bb\u7c07\u5fc3\u8ddd\u79bb')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u6587\u6863',
                'verbose_name_plural': '\u65b0\u95fb\u6587\u6863',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bdd\u9898\u540d\u79f0')),
                ('url', models.CharField(max_length=100, verbose_name='\u8bdd\u9898\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u8bdd\u9898',
                'verbose_name_plural': '\u65b0\u95fb\u8bdd\u9898',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_cluster.Topic', verbose_name='\u6240\u5c5e\u8bdd\u9898'),
        ),
    ]
